### ISSUE TITLE
Automatic choosing

### ISSUE THREAD

**Issue by hjmg** [atom/one-light-ui#101]
Good morming!
I have a problem with this theme, I can't choose another themes, and I tried change the file config.cson, but the file never change.
How to fixed this problem?

**Comment by hjmg** [comment]
Now the interface is broken when i tried to change the theme again, sorry.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
