### ISSUE TITLE
Non-core media queries make matching style difficult

### ISSUE THREAD

**Issue by ssorallen** [atom/one-light-ui#34]
The media queries used by one-light-ui and one-dark-ui are not part of Atom's "ui-variables", which means package/component authors cannot respond to the query changes appropriately. If the queries are actually desirable, they should maybe be moved to Atom's "ui-variables" or removed entirely.

**Comment by simurai** [comment]
> The media queries used by one-light-ui and one-dark-ui are not part of Atom's "ui-variables"

Are you refering to this: https://github.com/atom/one-light-ui/blob/master/styles/config.less

**Comment by ssorallen** [comment]
Yup yup, that's what I meant. I was working on a right panel and was trying to make it flush with the <atom-text-editor>. The media queries add padding in wider widths and remove them in narrower widths, but that's only in this theme. Granted I can't test all themes, I was hoping to at least work as expected in the 4 packaged themes.

**Comment by simurai** [comment]
The different layout modes (+ media queries) are something custom added to the One themes. Not sure how to standardize that in `ui-variables`.

I've seen packages (like toolbar) that add a right panel have specific styles for [certain themes](https://github.com/suda/tool-bar/tree/master/styles). Ideally that shouldn't be needed. In One theme's case, it just removes the borders, but keeps the padding if in spacious mode:

![screen shot 2015-08-27 at 4 58 01 pm](https://cloud.githubusercontent.com/assets/378023/9515466/d77afb1a-4cdc-11e5-9573-363c3b1121a1.png)

Would it be possible for your package to keep the padding in spacious mode too like that? So it wouldn't be flush with the editor. But maybe ok, since users *choose* to have some spacing around the editor.

**Comment by ssorallen** [comment]
The media queries feel misplaced to me. Media queries on websites are typically used to target various form factors: desktop, tablet, and mobile (perhaps those categories are subdivided further). Atom is targeting desktop.

In a text editor with high configurability, I expect the editor to exactly reflect my settings. With the font size and padding changing as I resize the window, I'm no longer in control. What does my font-size setting of "12" mean if the theme is going to change it or use a multiple of it?

I realize this is bikeshed territory though, so I'll close this and see if it's possible to ignore media query changes and still look and feel like I'd like.

**Comment by simurai** [comment]
> The media queries feel misplaced to me.

I agree it's uncommon for a desktop app, but UX wise it might still have some benefits. Like when you move between different monitor sizes. Or if you shrink Atom to make space for other windows. In that case it's nice having a more compact UI. For people that don't like that, they could lock it in the settings to always stay the same.

Packages that use the official `@font-size` variable from [ui-variables](https://github.com/atom/one-light-ui/blob/master/styles/ui-variables.less#L102) get a fixed `12px` and are not affected by the changes in the settings. Only the core UI adapts.

Is your package public? Would be interesting to see another use case.
