### ISSUE TITLE
Font Size setting for above 11, changes itself to 20

### ISSUE THREAD

**Issue by orcpac7** [atom/one-light-ui#47]
Trying to set font size of the theme. Atom version 1.2.4, check for updates says all installed packages are up to date.
To reproduce, from the menu select:
Packages, Settings View, Themes, UI Theme (One Light selected, click the gear to right of the Theme Name textbox.
Under Settings, Font Size (help text says: "Needs to be between 8 and 20")
Enter any number between 8 and 11. UI is refreshed with that size. (expected)
Enter any number between 12 and 20. UI is refreshed with 20 and 20 replaces the number you entered in the Font Size text input. (unexpected)

**Comment by simurai** [comment]
When selecting the last digit and then changing it, it works:

![font-size](https://cloud.githubusercontent.com/assets/378023/11604850/ea5599a8-9aa6-11e5-8022-444052b6386a.gif)

But I think the problem is:

1. if you are at `11` and want to go to `12`, you hit delete and it goes to `1`.
2. Because `1` is too small, it automatically changes to `8` (the minimum font size).
3. Then you type `2`. Which is now `82`. But since that is over the maximum, it changes to `20`.

It works if you type very quickly, but if the 2nd number gets typed after the auto-update, then it messes things up.

Not sure how to fix it.. maybe not auto-update if the number is below the minimum.

**Comment by orcpac7** [comment]
Thanks Simurai, your explanation makes sense.
So a workaround might be to type a size in notepad++, copy it, select the
existing size in the UI font size, and paste in the new size..
But your image seemed to imply that if one typed quickly, it wouldn't do
the resize dance. I'll have to try that.
I'm imagining that the the text size input probably has a keyPress handler
on it that fires for every character, and that needs be changed to an
onChange or equivalent event that doesn't get fired till you leave the
input and it has changed...

**Comment by simurai** [comment]
> if one typed quickly, it wouldn't do the resize dance.

Yeah, I seems like there is a short delay. Maybe like 1 second or so till the change gets applied. But often that's too quick.

**Comment by rsese** [comment]
More feedback about this issue in https://github.com/atom/atom/issues/16794.

**Comment by simurai** [comment]
Ok, let's do @edreamleo's [first suggestion](https://github.com/atom/atom/issues/16794#issuecomment-366998497) and use a dropdown:

![one](https://user-images.githubusercontent.com/378023/37138394-4433e45e-22ed-11e8-881d-6039ea63a112.gif)

**Comment by edreamleo** [comment]
On Thu, Mar 8, 2018 at 1:35 AM, simurai <notifications@github.com> wrote:

> Ok, let's do @edreamleo <https://github.com/edreamleo>'s first suggestion
> <https://github.com/atom/atom/issues/16794#issuecomment-366998497> and
> use a dropdown:
>
​Thanks!

Edward
