### ISSUE TITLE
Highlighted text in command palette

### ISSUE THREAD

**Issue by tobia** [atom/one-light-ui#70]
Just installed Atom on OS X and chose One Light theme and One Light syntax. No other package or customization. I'm seeing a shade of gray as the command palette highlight color that is not very readable. Is this an issue with this package or with something else?

![atom hl](https://cloud.githubusercontent.com/assets/48756/18084886/295a0644-6ea9-11e6-8fdd-a42a5234f45a.png)

**Comment by simurai** [comment]
I've seen this occasionally too. If you reload Atom, the color should be dark (and readable). Can you confirm that?

I think it's related to switching themes and something not getting updated correctly.

**Comment by tobia** [comment]
Yes, reloading make it dark.

I saw this issue when first installing Atom. The welcome screen prompted me to choose a theme and syntax; I chose One Light for both; and saw this issue.

**Comment by platy11** [comment]
I can reproduce this on Windows 7 with the following steps:

1. Change theme to Atom Dark
2. Restart Atom
3. Switch theme to One Light

**Comment by simurai** [comment]
@platy11 thanks for the reproduction steps! :ok_hand:

Not sure why [this variable](https://github.com/atom/command-palette/blob/master/styles/command-palette.less#L5) doesn't get picked up when switching themes after initial load. Very strange.. anyways.. it should be fixed with #87 and land in `1.14`.
